import { mkdir, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { PrismaClient } from "@prisma/client";
import { config } from "./config.js";
import { runCommand } from "./process.js";

function escapeCaddy(value: string) {
  return value.replace(/[^a-zA-Z0-9.-]/g, "");
}

export async function regenerateCaddyfile(prisma: PrismaClient) {
  const deployments = await prisma.deployment.findMany({
    where: {
      status: "running",
      containerName: { not: null },
      project: { status: "active" },
    },
    include: { project: { include: { domains: true } } },
    orderBy: { createdAt: "desc" },
  });

  const seenProjects = new Set<string>();
  const blocks: string[] = [];

  for (const deployment of deployments) {
    if (!deployment.containerName || seenProjects.has(deployment.projectId)) continue;
    seenProjects.add(deployment.projectId);

    for (const domain of deployment.project.domains.filter((item) => item.status === "active")) {
      blocks.push(`${escapeCaddy(domain.hostname)} {\n  encode zstd gzip\n  reverse_proxy ${escapeCaddy(deployment.containerName)}:${deployment.project.appPort}\n}`);
    }
  }

  const content = `# Generated by Cadsploy. Manual edits will be overwritten.\n\n${blocks.join("\n\n")}\n`;
  await mkdir(dirname(config.caddyfile), { recursive: true });
  await writeFile(config.caddyfile, content, "utf8");

  if (config.caddyReloadCommand.trim()) {
    const [command, ...args] = config.caddyReloadCommand.trim().split(/\s+/);
    if (command) await runCommand(command, args, { timeoutMs: 20_000 });
  }
}
